## provide the name of the namespace
namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

## define the image to execute with the Deployment 
image:
  repository:
     gbonjubee/techtrends
  tag: latest
  pullPolicy: Always

## set the number of replicas for an application 

replicaCount: 5

resources: 
  requests: 
    memory: 128Mi
    CPU: 350m
  limits: 
    memory: 256Mi
    CPU: 500m

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz